src/objects/Acao__c.object
<CustomObject>
    <label>Ação</label>
    <nameField>
        <label>Nome de Ação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Item_do_Plano__c.object
<CustomObject>
    <fields>
        <fullName>Acao__c</fullName>
        <label>Ação</label>
        <referenceTo>Acao__c</referenceTo>
        <relationshipLabel>Itens do Plano</relationshipLabel>
        <relationshipName>Itens_do_Plano</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plano_de_acao__c</fullName>
        <label>Plano de Ação</label>
        <referenceTo>Plano_de_acao__c</referenceTo>
        <relationshipLabel>Itens do Plano</relationshipLabel>
        <relationshipName>Itens_do_Plano</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Item do Plano</label>
    <nameField>
        <displayFormat>item-{0000}</displayFormat>
        <label>Nome de Item do Plano</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens do Plano</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plano_de_acao__c.object
<CustomObject>
    <label>Plano de Ação</label>
    <nameField>
        <label>Nome de Plano de Ação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de Ação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/novoItemDoPlano.cls
public with sharing class novoItemDoPlano {
    
    public Item_Do_Plano__c item{get; set;}
    public String itemID;
    public String acao {get;set;}
    
    public novoItemDoPlano(ApexPages.StandardController controller) {
        itemID = ApexPages.currentPage().getParameters().get('id');
        item = new Item_Do_Plano__c (Plano_de_acao__c=itemid);
    }
    public PageReference salvar(){
        item.acao__c = acao;
        insert item;
        PageReference requestPage = new pagereference('/' + itemId);
        requestPage.setRedirect(true);
        return requestPage;
   
    }
    public List<SelectOption> getAcoes() {
        List<SelectOption> acoes = new List<SelectOption>();
        Set<String> acids = new Set<String>();
        List<Item_do_Plano__c> ips = [Select Acao__c From Item_do_Plano__c Where Plano_de_acao__c =: itemId];
        for (Item_do_Plano__c x : ips){
            acids.add(x.Acao__c );
        }
        for (Acao__c x : [Select id, Name From Acao__c Where ID NOT IN : acids]){
            acoes.add(new SelectOption(x.Id,x.name));
        }
        return acoes;
    }
}