src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Nome de Merchandise</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MobileInventoryExtension.cls
public class MobileInventoryExtension {
 
  public MobileInventoryExtension(ApexPages.StandardController c) {}
  public MobileInventoryExtension(ApexPages.StandardSetController c) {}
    
  @RemoteAction
  public static String updateMerchandiseItem(String productId, Integer newInventory) {
   
    List<Merchandise__c> m = [SELECT Id, Name, Price__c, Quantity__c from Merchandise__c WHERE Id =: productId LIMIT 1];
    
    if(m.size() > 0) {
      m[0].Quantity__c = newInventory;
      try {
        update m[0];
        return 'Item Updated';
      }
      catch (Exception e) {
        return e.getMessage();
      }   
    }
    else {
      return 'No item found with that ID';
    }    
  } 
    @RemoteAction
  public static String removeMerchandiseItem(String productId) {
   
      List<Merchandise__c> m = [SELECT id from Merchandise__c WHERE Id =: productId];
     
      if(m.size() > 0){
      try {
        delete m;
        return 'Item Deleted';
      }
      catch (Exception e) {
        return e.getMessage();
      }   
    }
    else {
      return 'No item found with that ID';
    }    
  }
  @RemoteAction
  public static String createMerchandise(String name, Integer price, Integer quantity) {
   
    Merchandise__c m = new Merchandise__c();
    
    m.Name = name;
    m.Price__c = price;
    m.Quantity__c = quantity;
    
    if(m.Name != null) {
      try {
          insert m;
        return 'Item Created';
      }
      catch (Exception e) {
          return e.getMessage();
      }   
    }
    else {
      return 'Something went wrong. Could not create the merchandise.';
    }    
  }     
}