src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Nome de Merchandise</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StoreFrontController.cls
public class StoreFrontController {
        
        List<DisplayMerchandise> products;
        Set<DisplayMerchandise> carrinhoDeCompras = new Set<DisplayMerchandise>();
        
        public list<DisplayMerchandise> getProducts(){
                if(products == null){
                
                        products = new List<DisplayMerchandise>();
                        for(Merchandise__c item : [SELECT Id, Name, Price__c, Quantity__c FROM Merchandise__c]){
                                products.add(new DisplayMerchandise(item));
                        }
                }               
                return products;
        }
        public Pagereference addToCart(){       
                for(DisplayMerchandise p : products) {
                        if(0 < p.qtyToBuy) {
                            if(p.qtyToBuy <= p.quantity){
                                carrinhoDeCompras.add(p);
                            }
                        }
                }
                return null;
        }
       public String getCartContents() {
                if(0 == carrinhoDeCompras.size()) {
                        return '(empty)';
                }
                String msg = '<ul>\n';
                for(DisplayMerchandise p : carrinhoDeCompras) {
                        msg += '<li>';
                        msg += p.name + ' (' + p.qtyToBuy + ')';
                        msg += '</li>\n';
                }
        msg += '</ul>';
        return msg;
           }
}