src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Nome de Merchandise</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/canvasController.cls
public class canvasController {
    
        List<DisplayMerchandise> products;
        
        public list<DisplayMerchandise> getProducts(){
                if(products == null){
                
                        products = new List<DisplayMerchandise>();
                        for(Merchandise__c item : [SELECT Id, Name, Price__c, Quantity__c FROM Merchandise__c]){
                                products.add(new DisplayMerchandise(item));
                        }
                }               
                return products;
        }   
}