src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Nome de Merchandise</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DisplayMerchandise.cls
public class DisplayMerchandise {
        
                private Merchandise__c merchandise;
                public DisplayMerchandise(Merchandise__c item) {
                        this.merchandise = item;
                }
        
                public String name {
                        get { return merchandise.Name; }
                }
            	public Integer quantity{
                    get { return (Integer) merchandise.Quantity__c;}
            	}
                public Boolean inStock {
                        get { return (0 < merchandise.Quantity__c); }
                }
                public Decimal price {
                        get { return merchandise.Price__c; }
                }
                public Integer qtyToBuy { get; set; }
        }